spring:
  application:
    name: coworking-app
  datasource:
    url: jdbc:postgresql://dpg-d82ejefavr4c73dq1aag-a.oregon-postgres.render.com/coworking_db_doaz
    username: coworking_db_doaz_user
    password: V0cZsYd8fYrX8FqL8XMKP4pMVXkEpuCQ
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "clave-super-secreta-de-256-bits-para-coworking-app-espe"
  expiration-ms: 86400000